language: python
sudo: required
dist: xenial

# install dependencies
install:
  - pip install --upgrade setuptools pip
  # add --pre so that we test with prereleases of dependencies
  # to catch compatibility issues before they enter final releases
  - pip install --upgrade --pre -e ".[test]"
  - |
    # install pinned kubernetes
    if [[ ! -z "$KUBE_PY" ]]; then
      pip install "kubernetes==$KUBE_PY.*"
    fi
  - source ci/minikube.env
  - ./ci/install-kube.sh
  - pip freeze

# command to run tests
script:
  - pytest --cov kubespawner -v
after_success:
  - pip install codecov
  - codecov

matrix:
  fast_finish: true
  allow_failures:
    - env: KUBE_PY=11
  fast_finish: true
  include:
    - python: 3.5
      env: KUBE_PY=7
    - python: 3.6
      env: KUBE_PY=8
    - python: 3.7
      env: KUBE_PY=9
    - python: 3.8
      env: KUBE_PY=10
    - python: 3.8
      env: KUBE_PY=11
